controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

get_starting_price:
    path: '/stay/get_starting_price/{id}'
    controller: 'App\Controller\StayController::getStartingPrice'
    methods: ['GET']
